import csv
import io
import json
import zipfile
from typing import List, Dict, Any, Tuple

from qdrant_client.models import Filter, FieldCondition, MatchValue

from services.builder_graph import get_neo4j_driver


def export_qdrant_points(q_client, collection_name: str, project_name: str) -> List[Dict[str, Any]]:
    """Paginates through every Qdrant point tagged with this project and returns id/vector/payload."""
    points: List[Dict[str, Any]] = []
    offset = None
    q_filter = Filter(must=[FieldCondition(key="project_name", match=MatchValue(value=project_name))])

    while True:
        batch, offset = q_client.scroll(
            collection_name=collection_name,
            scroll_filter=q_filter,
            limit=256,
            offset=offset,
            with_payload=True,
            with_vectors=True,
        )
        for p in batch:
            points.append({"id": p.id, "vector": p.vector, "payload": p.payload})
        if offset is None:
            break

    return points


def export_neo4j_triplets(project_name: str) -> List[Dict[str, Any]]:
    """Fetches every CONNECTED_TO edge belonging to this project from Neo4j."""
    driver = get_neo4j_driver()
    if not driver:
        return []

    rows: List[Dict[str, Any]] = []
    try:
        with driver.session() as session:
            result = session.run(
                """
                MATCH (s:Entity {project: $project})-[r:CONNECTED_TO {project: $project}]->(t:Entity {project: $project})
                RETURN s.id AS source, r.type AS relation, t.id AS target, r.source_text AS source_text, r.source_doc AS source_doc
                """,
                project=project_name,
            )
            for record in result:
                rows.append(dict(record))
    finally:
        driver.close()

    return rows


def _build_triplets_csv(triplets: List[Dict[str, Any]]) -> str:
    buffer = io.StringIO()
    writer = csv.DictWriter(buffer, fieldnames=["source", "relation", "target", "source_text", "source_doc"])
    writer.writeheader()
    for row in triplets:
        writer.writerow(row)
    return buffer.getvalue()


def _build_triplets_cypher(triplets: List[Dict[str, Any]], project_name: str) -> str:
    lines = [
        "// Re-import script generated by RAGner export",
        "CREATE CONSTRAINT IF NOT EXISTS FOR (e:Entity) REQUIRE (e.id, e.project) IS UNIQUE;",
        "",
    ]
    for t in triplets:
        source = json.dumps(t.get("source", ""))
        target = json.dumps(t.get("target", ""))
        relation = json.dumps(t.get("relation", "CONNECTED_TO"))
        source_text = json.dumps(t.get("source_text", ""))
        source_doc = json.dumps(t.get("source_doc", ""))
        project = json.dumps(project_name)
        lines.append(
            f"MERGE (s:Entity {{id: {source}, project: {project}}}) "
            f"MERGE (t:Entity {{id: {target}, project: {project}}}) "
            f"MERGE (s)-[r:CONNECTED_TO {{type: {relation}, project: {project}}}]->(t) "
            f"ON CREATE SET r.source_text = {source_text}, r.source_doc = {source_doc};"
        )
    return "\n".join(lines)


def build_export_zip(q_client, collection_name: str, project_name: str) -> Tuple[io.BytesIO, int, int]:
    """
    Bundles this project's Qdrant vectors/payloads and Neo4j triplets into an in-memory zip.
    NOTE: this endpoint is not payment-gated server-side yet -- the frontend simulates the
    one-time $8 checkout before calling it. Add real payment/session verification here
    before this goes to production.
    """
    points = export_qdrant_points(q_client, collection_name, project_name)
    triplets = export_neo4j_triplets(project_name)

    readme = f"""RAGner Data Export -- project: {project_name}

Contents:
  qdrant_vectors.json  - every vector + payload stored for this project in Qdrant.
                         Each entry: {{ "id", "vector", "payload" }}.
  neo4j_triplets.csv   - every knowledge-graph edge for this project as a flat table
                         (source, relation, target, source_text, source_doc).
  neo4j_import.cypher  - the same triplets as ready-to-run MERGE statements. Import with:
                         cypher-shell -u <user> -p <password> -f neo4j_import.cypher

Exported {len(points)} vector(s) and {len(triplets)} triplet(s).
"""

    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("qdrant_vectors.json", json.dumps(points, indent=2, default=str))
        zf.writestr("neo4j_triplets.csv", _build_triplets_csv(triplets))
        zf.writestr("neo4j_import.cypher", _build_triplets_cypher(triplets, project_name))
        zf.writestr("README.txt", readme)

    zip_buffer.seek(0)
    return zip_buffer, len(points), len(triplets)
