import os
import uuid
from typing import List, Dict, Any
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct
from dotenv import load_dotenv

load_dotenv()

def get_qdrant_client() -> QdrantClient:
    """
    Connects to the local Qdrant Docker container.
    Ensure Docker is running and you have executed: docker run -p 6333:6333 qdrant/qdrant
    """
    qdrant_url = os.getenv("QDRANT_URL", "http://localhost:6333")
    qdrant_api_key = os.getenv("QDRANT_API_KEY", None)

    if qdrant_api_key:
        print("Connecting to Managed Qdrant Cloud...")
        return QdrantClient(url=qdrant_url, api_key=qdrant_api_key)
    
    print("Connecting to Local Qdrant Docker...")
    return QdrantClient(url=qdrant_url)

def init_collection(client: QdrantClient, collection_name: str, vector_size=1536):
    """
    Creates a new collection in Qdrant if it doesn't exist.
    A 'collection' in Qdrant is like a table in a relational database.
    """
    if not client.collection_exists(collection_name=collection_name):
        print(f"Creating collection: {collection_name}")
        client.create_collection(
            collection_name=collection_name,
            vectors_config=VectorParams(
                size=vector_size, 
                distance=Distance.COSINE # Cosine similarity is standard for text embeddings, we can shift to EUCLIDEAN if we want.
            ),
        )
    else:
        print(f"Collection '{collection_name}' already exists.")

def upsert_chunks(client: QdrantClient, collection_name: str, chunks: List[Dict[str, Any]], embedder):
    """
    Takes the chunks generated by our chunking service, embeds the text, 
    and uploads the vectors + metadata to Qdrant.
    """
    if not chunks:
        print("No chunks provided to upsert.")
        return

    print(f"Embedding and upserting {len(chunks)} chunks...")

    texts_to_embed = [chunk["text"] for chunk in chunks]
    embeddings = embedder.embed_documents(texts_to_embed)

    points = [] # Qdrant Points
    for i, chunk in enumerate(chunks):
        point_id = str(uuid.uuid4())
        payload = {
            "text": chunk["text"],
            **chunk["metadata"] 
        }
        point = PointStruct(id=point_id, vector=embeddings[i], payload=payload)
        points.append(point)

    client.upsert(
        collection_name=collection_name,
        points=points
    )
    print("Upsert complete!")
